### ISSUE TITLE
Can't change incorrect consumer key

### ISSUE THREAD

**Issue by jordanrolph** [SeanBE/pocket-retro#29]
I input an incorrect consumer key (typo) so the Pocket authentication failed. 

The incorrect key is stored by the app somehow. I tried to refresh but the authentication keeps failing because it remembers the incorrect key.

**Comment by SeanBE** [comment]
Thanks for this issue! I store the key in local storage but I see how this becomes a hassle to reset if its invalid.

I've added the option to reset consumer keys manually when any of the pocket endpoints fail. You can pull the latest from dockerhub now (https://hub.docker.com/r/seanbe/pocket_retro)
